//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40607.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Sideris.Properties {
    using System;
    using System.IO;
    using System.Resources;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the Strongly Typed Resource Builder
    // class via a tool like ResGen or Visual Studio.NET.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    class Resources {
        
        private static System.Resources.ResourceManager _resMgr;
        
        private static System.Globalization.CultureInfo _resCulture;
        
        /*FamANDAssem*/ internal Resources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if ((_resMgr == null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Sideris.Properties.Resources", typeof(Resources).Assembly);
                    _resMgr = temp;
                }
                return _resMgr;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return _resCulture;
            }
            set {
                _resCulture = value;
            }
        }
        
        public static System.Drawing.Bitmap Cancel {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Cancel", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Chat {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Chat", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Connect0 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Connect0", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Connect1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Connect1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Connect2 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Connect2", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Connect3 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Connect3", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Connect4 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Connect4", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap ConnectDo_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ConnectDo.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap ConnectDo_png_4 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ConnectDo.png.4", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap ConnectDrop_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ConnectDrop.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap ConnectDrop_png_4 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ConnectDrop.png.4", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap ConnectedHighHigh_png_0 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("ConnectedHighHigh.png.0", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Copy_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Copy.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Delete_png_2 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Delete.png.2", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap FileInfo_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FileInfo.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap FileOpen_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FileOpen.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap FilePriority_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FilePriority.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap FileRename_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FileRename.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap FolderOpen_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FolderOpen.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Folders_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Folders.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Global_png_2 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Global.png.2", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Info_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Info.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Pause_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Pause.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Preferences_png_0 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Preferences.png.0", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Preferences_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Preferences.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Preview_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Preview.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Priority_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Priority.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Search_png_5 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Search.png.5", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap SearchResults_png_2 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("SearchResults.png.2", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Security_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Security.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap SharedFiles_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("SharedFiles.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap SharedFiles_png_2 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("SharedFiles.png.2", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap SpeedMin_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("SpeedMin.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Start_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Start.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Stop_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Stop.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Tools_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Tools.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Transfer_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Transfer.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Web_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Web.png.1", _resCulture)));
            }
        }
        
        public static System.Drawing.Bitmap Wizzard_png_1 {
            get {
                return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Wizzard.png.1", _resCulture)));
            }
        }
    }
}
