//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sideris.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sideris.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Chat {
            get {
                object obj = ResourceManager.GetObject("Chat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connect0 {
            get {
                object obj = ResourceManager.GetObject("Connect0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connect1 {
            get {
                object obj = ResourceManager.GetObject("Connect1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connect2 {
            get {
                object obj = ResourceManager.GetObject("Connect2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connect3 {
            get {
                object obj = ResourceManager.GetObject("Connect3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Connect4 {
            get {
                object obj = ResourceManager.GetObject("Connect4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectDo_png_1 {
            get {
                object obj = ResourceManager.GetObject("ConnectDo.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectDo_png_4 {
            get {
                object obj = ResourceManager.GetObject("ConnectDo.png.4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectDrop_png_1 {
            get {
                object obj = ResourceManager.GetObject("ConnectDrop.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectDrop_png_4 {
            get {
                object obj = ResourceManager.GetObject("ConnectDrop.png.4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ConnectedHighHigh_png_0 {
            get {
                object obj = ResourceManager.GetObject("ConnectedHighHigh.png.0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Copy_png_1 {
            get {
                object obj = ResourceManager.GetObject("Copy.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Delete_png_2 {
            get {
                object obj = ResourceManager.GetObject("Delete.png.2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileInfo_png_1 {
            get {
                object obj = ResourceManager.GetObject("FileInfo.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileOpen_png_1 {
            get {
                object obj = ResourceManager.GetObject("FileOpen.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FilePriority_png_1 {
            get {
                object obj = ResourceManager.GetObject("FilePriority.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FileRename_png_1 {
            get {
                object obj = ResourceManager.GetObject("FileRename.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap FolderOpen_png_1 {
            get {
                object obj = ResourceManager.GetObject("FolderOpen.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Folders_png_1 {
            get {
                object obj = ResourceManager.GetObject("Folders.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Global_png_2 {
            get {
                object obj = ResourceManager.GetObject("Global.png.2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Info_png_1 {
            get {
                object obj = ResourceManager.GetObject("Info.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Pause_png_1 {
            get {
                object obj = ResourceManager.GetObject("Pause.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Preferences_png_0 {
            get {
                object obj = ResourceManager.GetObject("Preferences.png.0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Preferences_png_1 {
            get {
                object obj = ResourceManager.GetObject("Preferences.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Preview_png_1 {
            get {
                object obj = ResourceManager.GetObject("Preview.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Priority_png_1 {
            get {
                object obj = ResourceManager.GetObject("Priority.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Search_png_5 {
            get {
                object obj = ResourceManager.GetObject("Search.png.5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SearchResults_png_2 {
            get {
                object obj = ResourceManager.GetObject("SearchResults.png.2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Security_png_1 {
            get {
                object obj = ResourceManager.GetObject("Security.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SharedFiles_png_1 {
            get {
                object obj = ResourceManager.GetObject("SharedFiles.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SharedFiles_png_2 {
            get {
                object obj = ResourceManager.GetObject("SharedFiles.png.2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SpeedMin_png_1 {
            get {
                object obj = ResourceManager.GetObject("SpeedMin.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Start_png_1 {
            get {
                object obj = ResourceManager.GetObject("Start.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Stop_png_1 {
            get {
                object obj = ResourceManager.GetObject("Stop.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Tools_png_1 {
            get {
                object obj = ResourceManager.GetObject("Tools.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Transfer_png_1 {
            get {
                object obj = ResourceManager.GetObject("Transfer.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Web_png_1 {
            get {
                object obj = ResourceManager.GetObject("Web.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Wizzard_png_1 {
            get {
                object obj = ResourceManager.GetObject("Wizzard.png.1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
