//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version:2.0.40607.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace Sideris {
    using System;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("FilesDataSet")]
    public partial class FilesDataSet : System.Data.DataSet {
        
        private SharesDataTable tableShares;
        
        private DownloadsDataTable tableDownloads;
        
        public FilesDataSet() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        protected FilesDataSet(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Shares"] != null)) {
                    base.Tables.Add(new SharesDataTable(ds.Tables["Shares"]));
                }
                if ((ds.Tables["Downloads"] != null)) {
                    base.Tables.Add(new DownloadsDataTable(ds.Tables["Downloads"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public SharesDataTable Shares {
            get {
                return this.tableShares;
            }
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public DownloadsDataTable Downloads {
            get {
                return this.tableDownloads;
            }
        }
        
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.ComponentModel.DefaultValueAttribute(false)]
        public new bool EnforceConstraints {
            get {
                return base.EnforceConstraints;
            }
            set {
                base.EnforceConstraints = value;
            }
        }
        
        public override System.Data.DataSet Clone() {
            FilesDataSet cln = ((FilesDataSet)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            this.Reset();
            System.Data.DataSet ds = new System.Data.DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Shares"] != null)) {
                base.Tables.Add(new SharesDataTable(ds.Tables["Shares"]));
            }
            if ((ds.Tables["Downloads"] != null)) {
                base.Tables.Add(new DownloadsDataTable(ds.Tables["Downloads"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.InitVars(true);
        }
        
        internal void InitVars(bool initTable) {
            this.tableShares = ((SharesDataTable)(base.Tables["Shares"]));
            if ((initTable == true)) {
                if ((this.tableShares != null)) {
                    this.tableShares.InitVars();
                }
            }
            this.tableDownloads = ((DownloadsDataTable)(base.Tables["Downloads"]));
            if ((initTable == true)) {
                if ((this.tableDownloads != null)) {
                    this.tableDownloads.InitVars();
                }
            }
        }
        
        private void InitClass() {
            this.DataSetName = "FilesDataSet";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/Sideris.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = false;
            this.tableShares = new SharesDataTable();
            base.Tables.Add(this.tableShares);
            this.tableDownloads = new DownloadsDataTable();
            base.Tables.Add(this.tableDownloads);
            this.ExtendedProperties.Add("DSGenerator_DataSetName", "FilesDataSet");
            this.ExtendedProperties.Add("User_DataSetName", "FilesDataSet");
        }
        
        private bool ShouldSerializeShares() {
            return false;
        }
        
        private bool ShouldSerializeDownloads() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            FilesDataSet ds = new FilesDataSet();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            if (PublishLegacyWSDL()) {
                System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
                any.Namespace = ds.Namespace;
                sequence.Items.Add(any);
            }
            else {
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(0);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                sequence.MaxOccurs = decimal.MaxValue;
                System.Xml.Schema.XmlSchemaAttribute attribute = new System.Xml.Schema.XmlSchemaAttribute();
                attribute.Name = "namespace";
                attribute.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute);
            }
            type.Particle = sequence;
            return type;
        }
        
        protected static bool PublishLegacyWSDL() {
            System.Collections.Specialized.NameValueCollection settings = ((System.Collections.Specialized.NameValueCollection)(System.Configuration.ConfigurationSettings.GetConfig("system.data.dataset")));
            if ((settings != null)) {
                string[] values = settings.GetValues("WSDL_VERSION");
                if ((values != null)) {
                    float version = float.Parse(((string)(values[0])), ((System.IFormatProvider)(null)));
                    return (version < 2);
                }
            }
            return true;
        }
        
        public delegate void SharesRowChangeEventHandler(object sender, SharesRowChangeEvent e);
        
        public delegate void DownloadsRowChangeEventHandler(object sender, DownloadsRowChangeEvent e);
        
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class SharesDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnFullName;
            
            private System.Data.DataColumn columnHash;
            
            private System.Data.DataColumn columnLastModified;
            
            private System.Data.DataColumn columnSize;
            
            private System.Data.DataColumn columnKeep;
            
            private bool m_suspendValidation = false;
            
            public SharesDataTable() {
                this.TableName = "Shares";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            internal SharesDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            protected SharesDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            internal System.Data.DataColumn FullNameColumn {
                get {
                    return this.columnFullName;
                }
            }
            
            internal System.Data.DataColumn HashColumn {
                get {
                    return this.columnHash;
                }
            }
            
            internal System.Data.DataColumn LastModifiedColumn {
                get {
                    return this.columnLastModified;
                }
            }
            
            internal System.Data.DataColumn SizeColumn {
                get {
                    return this.columnSize;
                }
            }
            
            internal System.Data.DataColumn KeepColumn {
                get {
                    return this.columnKeep;
                }
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            public SharesRow this[int index] {
                get {
                    return ((SharesRow)(this.Rows[index]));
                }
            }
            
            public bool SuspendValidation {
                get {
                    return this.m_suspendValidation;
                }
                set {
                    this.m_suspendValidation = value;
                }
            }
            
            public event FullNameChangeEventHandler FullNameChanging;
            
            public event FullNameChangeEventHandler FullNameChanged;
            
            public event HashChangeEventHandler HashChanging;
            
            public event HashChangeEventHandler HashChanged;
            
            public event LastModifiedChangeEventHandler LastModifiedChanging;
            
            public event LastModifiedChangeEventHandler LastModifiedChanged;
            
            public event SizeChangeEventHandler SizeChanging;
            
            public event SizeChangeEventHandler SizeChanged;
            
            public event KeepChangeEventHandler KeepChanging;
            
            public event KeepChangeEventHandler KeepChanged;
            
            public event SharesRowChangeEventHandler SharesRowChanged;
            
            public event SharesRowChangeEventHandler SharesRowChanging;
            
            public event SharesRowChangeEventHandler SharesRowDeleted;
            
            public event SharesRowChangeEventHandler SharesRowDeleting;
            
            protected override void OnColumnChanging(System.Data.DataColumnChangeEventArgs e) {
                base.OnColumnChanging(e);
                if ((this.SuspendValidation == true)) {
                    return;
                }
                if ((e.Column.ColumnName == "FullName")) {
                    if ((this.FullNameChanging != null)) {
                        this.FullNameChanging(this, new FullNameChangeEventArg(e));
                    }
                }
                else {
                    if ((e.Column.ColumnName == "Hash")) {
                        if ((this.HashChanging != null)) {
                            this.HashChanging(this, new HashChangeEventArg(e));
                        }
                    }
                    else {
                        if ((e.Column.ColumnName == "LastModified")) {
                            if ((this.LastModifiedChanging != null)) {
                                this.LastModifiedChanging(this, new LastModifiedChangeEventArg(e));
                            }
                        }
                        else {
                            if ((e.Column.ColumnName == "Size")) {
                                if ((this.SizeChanging != null)) {
                                    this.SizeChanging(this, new SizeChangeEventArg(e));
                                }
                            }
                            else {
                                if ((e.Column.ColumnName == "Keep")) {
                                    if ((this.KeepChanging != null)) {
                                        this.KeepChanging(this, new KeepChangeEventArg(e));
                                    }
                                }
                            }
                        }
                    }
                }
            }
            
            protected override void OnColumnChanged(System.Data.DataColumnChangeEventArgs e) {
                base.OnColumnChanged(e);
                if ((this.SuspendValidation == true)) {
                    return;
                }
                if ((e.Column.ColumnName == "FullName")) {
                    if ((this.FullNameChanged != null)) {
                        this.FullNameChanged(this, new FullNameChangeEventArg(e));
                    }
                }
                else {
                    if ((e.Column.ColumnName == "Hash")) {
                        if ((this.HashChanged != null)) {
                            this.HashChanged(this, new HashChangeEventArg(e));
                        }
                    }
                    else {
                        if ((e.Column.ColumnName == "LastModified")) {
                            if ((this.LastModifiedChanged != null)) {
                                this.LastModifiedChanged(this, new LastModifiedChangeEventArg(e));
                            }
                        }
                        else {
                            if ((e.Column.ColumnName == "Size")) {
                                if ((this.SizeChanged != null)) {
                                    this.SizeChanged(this, new SizeChangeEventArg(e));
                                }
                            }
                            else {
                                if ((e.Column.ColumnName == "Keep")) {
                                    if ((this.KeepChanged != null)) {
                                        this.KeepChanged(this, new KeepChangeEventArg(e));
                                    }
                                }
                            }
                        }
                    }
                }
            }
            
            public void AddSharesRow(SharesRow row) {
                this.Rows.Add(row);
            }
            
            public SharesRow AddSharesRow(string FullName, string Hash, System.DateTime LastModified, long Size, bool Keep) {
                SharesRow rowSharesRow = ((SharesRow)(this.NewRow()));
                rowSharesRow.ItemArray = new object[] {
                        FullName,
                        Hash,
                        LastModified,
                        Size,
                        Keep};
                this.Rows.Add(rowSharesRow);
                return rowSharesRow;
            }
            
            public SharesRow FindByFullName(string FullName) {
                return ((SharesRow)(this.Rows.Find(new object[] {
                            FullName})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override System.Data.DataTable Clone() {
                SharesDataTable cln = ((SharesDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override System.Data.DataTable CreateInstance() {
                return new SharesDataTable();
            }
            
            internal void InitVars() {
                this.columnFullName = base.Columns["FullName"];
                this.columnHash = base.Columns["Hash"];
                this.columnLastModified = base.Columns["LastModified"];
                this.columnSize = base.Columns["Size"];
                this.columnKeep = base.Columns["Keep"];
            }
            
            private void InitClass() {
                this.columnFullName = new System.Data.DataColumn("FullName", typeof(string), null, System.Data.MappingType.Element);
                this.columnFullName.ExtendedProperties.Add("Generator_ChangedEventName", "FullNameChanged");
                this.columnFullName.ExtendedProperties.Add("Generator_ChangingEventName", "FullNameChanging");
                this.columnFullName.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "FullName");
                this.columnFullName.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "FullNameColumn");
                this.columnFullName.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnFullName");
                this.columnFullName.ExtendedProperties.Add("Generator_DelegateName", "FullNameChangeEventHandler");
                this.columnFullName.ExtendedProperties.Add("Generator_EventArgName", "FullNameChangeEventArg");
                this.columnFullName.ExtendedProperties.Add("User_ColumnName", "FullName");
                base.Columns.Add(this.columnFullName);
                this.columnHash = new System.Data.DataColumn("Hash", typeof(string), null, System.Data.MappingType.Element);
                this.columnHash.ExtendedProperties.Add("Generator_ChangedEventName", "HashChanged");
                this.columnHash.ExtendedProperties.Add("Generator_ChangingEventName", "HashChanging");
                this.columnHash.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Hash");
                this.columnHash.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "HashColumn");
                this.columnHash.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnHash");
                this.columnHash.ExtendedProperties.Add("Generator_DelegateName", "HashChangeEventHandler");
                this.columnHash.ExtendedProperties.Add("Generator_EventArgName", "HashChangeEventArg");
                this.columnHash.ExtendedProperties.Add("User_ColumnName", "Hash");
                base.Columns.Add(this.columnHash);
                this.columnLastModified = new System.Data.DataColumn("LastModified", typeof(System.DateTime), null, System.Data.MappingType.Element);
                this.columnLastModified.ExtendedProperties.Add("Generator_ChangedEventName", "LastModifiedChanged");
                this.columnLastModified.ExtendedProperties.Add("Generator_ChangingEventName", "LastModifiedChanging");
                this.columnLastModified.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "LastModified");
                this.columnLastModified.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "LastModifiedColumn");
                this.columnLastModified.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnLastModified");
                this.columnLastModified.ExtendedProperties.Add("Generator_DelegateName", "LastModifiedChangeEventHandler");
                this.columnLastModified.ExtendedProperties.Add("Generator_EventArgName", "LastModifiedChangeEventArg");
                this.columnLastModified.ExtendedProperties.Add("User_ColumnName", "LastModified");
                base.Columns.Add(this.columnLastModified);
                this.columnSize = new System.Data.DataColumn("Size", typeof(long), null, System.Data.MappingType.Element);
                this.columnSize.ExtendedProperties.Add("Generator_ChangedEventName", "SizeChanged");
                this.columnSize.ExtendedProperties.Add("Generator_ChangingEventName", "SizeChanging");
                this.columnSize.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Size");
                this.columnSize.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "SizeColumn");
                this.columnSize.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnSize");
                this.columnSize.ExtendedProperties.Add("Generator_DelegateName", "SizeChangeEventHandler");
                this.columnSize.ExtendedProperties.Add("Generator_EventArgName", "SizeChangeEventArg");
                this.columnSize.ExtendedProperties.Add("User_ColumnName", "Size");
                base.Columns.Add(this.columnSize);
                this.columnKeep = new System.Data.DataColumn("Keep", typeof(bool), null, System.Data.MappingType.Element);
                this.columnKeep.ExtendedProperties.Add("Generator_ChangedEventName", "KeepChanged");
                this.columnKeep.ExtendedProperties.Add("Generator_ChangingEventName", "KeepChanging");
                this.columnKeep.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Keep");
                this.columnKeep.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "KeepColumn");
                this.columnKeep.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnKeep");
                this.columnKeep.ExtendedProperties.Add("Generator_DelegateName", "KeepChangeEventHandler");
                this.columnKeep.ExtendedProperties.Add("Generator_EventArgName", "KeepChangeEventArg");
                this.columnKeep.ExtendedProperties.Add("User_ColumnName", "Keep");
                base.Columns.Add(this.columnKeep);
                this.Constraints.Add(new System.Data.UniqueConstraint("HashKey", new System.Data.DataColumn[] {
                                this.columnHash}, false));
                this.Constraints.Add(new System.Data.UniqueConstraint("NameKey", new System.Data.DataColumn[] {
                                this.columnFullName}, true));
                this.columnFullName.AllowDBNull = false;
                this.columnFullName.Unique = true;
                this.columnHash.Unique = true;
                this.ExtendedProperties.Add("Generator_RowClassName", "SharesRow");
                this.ExtendedProperties.Add("Generator_RowEvArgName", "SharesRowChangeEvent");
                this.ExtendedProperties.Add("Generator_RowEvHandlerName", "SharesRowChangeEventHandler");
                this.ExtendedProperties.Add("Generator_SuspendValidationPropName", "SuspendValidation");
                this.ExtendedProperties.Add("Generator_SuspendValidationVarName", "m_suspendValidation");
                this.ExtendedProperties.Add("Generator_TableClassName", "SharesDataTable");
                this.ExtendedProperties.Add("Generator_TablePropName", "Shares");
                this.ExtendedProperties.Add("Generator_TableVarName", "tableShares");
                this.ExtendedProperties.Add("User_TableName", "Shares");
            }
            
            public SharesRow NewSharesRow() {
                return ((SharesRow)(this.NewRow()));
            }
            
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new SharesRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(SharesRow);
            }
            
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.SharesRowChanged != null)) {
                    this.SharesRowChanged(this, new SharesRowChangeEvent(((SharesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.SharesRowChanging != null)) {
                    this.SharesRowChanging(this, new SharesRowChangeEvent(((SharesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.SharesRowDeleted != null)) {
                    this.SharesRowDeleted(this, new SharesRowChangeEvent(((SharesRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.SharesRowDeleting != null)) {
                    this.SharesRowDeleting(this, new SharesRowChangeEvent(((SharesRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveSharesRow(SharesRow row) {
                this.Rows.Remove(row);
            }
            
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                FilesDataSet ds = new FilesDataSet();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "SharesDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
            
            public delegate void FullNameChangeEventHandler(SharesDataTable sender, FullNameChangeEventArg e);
            
            public class FullNameChangeEventArg : System.EventArgs {
                
                private System.Data.DataColumnChangeEventArgs evArgs;
                
                public FullNameChangeEventArg(System.Data.DataColumnChangeEventArgs args) {
                    this.evArgs = args;
                }
                
                public SharesRow Row {
                    get {
                        return ((SharesRow)(this.evArgs.Row));
                    }
                }
                
                public System.Data.DataColumn FullNameColumn {
                    get {
                        return this.evArgs.Column;
                    }
                }
                
                public string ProposedValue {
                    get {
                        return ((string)(this.evArgs.ProposedValue));
                    }
                    set {
                        this.evArgs.ProposedValue = ((string)(value));
                    }
                }
            }
            
            public delegate void HashChangeEventHandler(SharesDataTable sender, HashChangeEventArg e);
            
            public class HashChangeEventArg : System.EventArgs {
                
                private System.Data.DataColumnChangeEventArgs evArgs;
                
                public HashChangeEventArg(System.Data.DataColumnChangeEventArgs args) {
                    this.evArgs = args;
                }
                
                public SharesRow Row {
                    get {
                        return ((SharesRow)(this.evArgs.Row));
                    }
                }
                
                public System.Data.DataColumn HashColumn {
                    get {
                        return this.evArgs.Column;
                    }
                }
                
                public string ProposedValue {
                    get {
                        return ((string)(this.evArgs.ProposedValue));
                    }
                    set {
                        this.evArgs.ProposedValue = ((string)(value));
                    }
                }
            }
            
            public delegate void LastModifiedChangeEventHandler(SharesDataTable sender, LastModifiedChangeEventArg e);
            
            public class LastModifiedChangeEventArg : System.EventArgs {
                
                private System.Data.DataColumnChangeEventArgs evArgs;
                
                public LastModifiedChangeEventArg(System.Data.DataColumnChangeEventArgs args) {
                    this.evArgs = args;
                }
                
                public SharesRow Row {
                    get {
                        return ((SharesRow)(this.evArgs.Row));
                    }
                }
                
                public System.Data.DataColumn LastModifiedColumn {
                    get {
                        return this.evArgs.Column;
                    }
                }
                
                public System.DateTime ProposedValue {
                    get {
                        return ((System.DateTime)(this.evArgs.ProposedValue));
                    }
                    set {
                        this.evArgs.ProposedValue = ((System.DateTime)(value));
                    }
                }
            }
            
            public delegate void SizeChangeEventHandler(SharesDataTable sender, SizeChangeEventArg e);
            
            public class SizeChangeEventArg : System.EventArgs {
                
                private System.Data.DataColumnChangeEventArgs evArgs;
                
                public SizeChangeEventArg(System.Data.DataColumnChangeEventArgs args) {
                    this.evArgs = args;
                }
                
                public SharesRow Row {
                    get {
                        return ((SharesRow)(this.evArgs.Row));
                    }
                }
                
                public System.Data.DataColumn SizeColumn {
                    get {
                        return this.evArgs.Column;
                    }
                }
                
                public long ProposedValue {
                    get {
                        return ((long)(this.evArgs.ProposedValue));
                    }
                    set {
                        this.evArgs.ProposedValue = ((long)(value));
                    }
                }
            }
            
            public delegate void KeepChangeEventHandler(SharesDataTable sender, KeepChangeEventArg e);
            
            public class KeepChangeEventArg : System.EventArgs {
                
                private System.Data.DataColumnChangeEventArgs evArgs;
                
                public KeepChangeEventArg(System.Data.DataColumnChangeEventArgs args) {
                    this.evArgs = args;
                }
                
                public SharesRow Row {
                    get {
                        return ((SharesRow)(this.evArgs.Row));
                    }
                }
                
                public System.Data.DataColumn KeepColumn {
                    get {
                        return this.evArgs.Column;
                    }
                }
                
                public bool ProposedValue {
                    get {
                        return ((bool)(this.evArgs.ProposedValue));
                    }
                    set {
                        this.evArgs.ProposedValue = ((bool)(value));
                    }
                }
            }
        }
        
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class DownloadsDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnFullName;
            
            private System.Data.DataColumn columnHash;
            
            private System.Data.DataColumn columnSize;
            
            private System.Data.DataColumn columnFileID;
            
            private System.Data.DataColumn columnOffset;
            
            private System.Data.DataColumn columnStatus;
            
            private bool m_suspendValidation = false;
            
            public DownloadsDataTable() {
                this.TableName = "Downloads";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            internal DownloadsDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            protected DownloadsDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            internal System.Data.DataColumn FullNameColumn {
                get {
                    return this.columnFullName;
                }
            }
            
            internal System.Data.DataColumn HashColumn {
                get {
                    return this.columnHash;
                }
            }
            
            internal System.Data.DataColumn SizeColumn {
                get {
                    return this.columnSize;
                }
            }
            
            internal System.Data.DataColumn FileIDColumn {
                get {
                    return this.columnFileID;
                }
            }
            
            internal System.Data.DataColumn OffsetColumn {
                get {
                    return this.columnOffset;
                }
            }
            
            internal System.Data.DataColumn StatusColumn {
                get {
                    return this.columnStatus;
                }
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            public DownloadsRow this[int index] {
                get {
                    return ((DownloadsRow)(this.Rows[index]));
                }
            }
            
            public bool SuspendValidation {
                get {
                    return this.m_suspendValidation;
                }
                set {
                    this.m_suspendValidation = value;
                }
            }
            
            public event FullNameChangeEventHandler FullNameChanging;
            
            public event FullNameChangeEventHandler FullNameChanged;
            
            public event HashChangeEventHandler HashChanging;
            
            public event HashChangeEventHandler HashChanged;
            
            public event SizeChangeEventHandler SizeChanging;
            
            public event SizeChangeEventHandler SizeChanged;
            
            public event FileIDChangeEventHandler FileIDChanging;
            
            public event FileIDChangeEventHandler FileIDChanged;
            
            public event OffsetChangeEventHandler OffsetChanging;
            
            public event OffsetChangeEventHandler OffsetChanged;
            
            public event StatusChangeEventHandler StatusChanging;
            
            public event StatusChangeEventHandler StatusChanged;
            
            public event DownloadsRowChangeEventHandler DownloadsRowChanged;
            
            public event DownloadsRowChangeEventHandler DownloadsRowChanging;
            
            public event DownloadsRowChangeEventHandler DownloadsRowDeleted;
            
            public event DownloadsRowChangeEventHandler DownloadsRowDeleting;
            
            protected override void OnColumnChanging(System.Data.DataColumnChangeEventArgs e) {
                base.OnColumnChanging(e);
                if ((this.SuspendValidation == true)) {
                    return;
                }
                if ((e.Column.ColumnName == "FullName")) {
                    if ((this.FullNameChanging != null)) {
                        this.FullNameChanging(this, new FullNameChangeEventArg(e));
                    }
                }
                else {
                    if ((e.Column.ColumnName == "Hash")) {
                        if ((this.HashChanging != null)) {
                            this.HashChanging(this, new HashChangeEventArg(e));
                        }
                    }
                    else {
                        if ((e.Column.ColumnName == "Size")) {
                            if ((this.SizeChanging != null)) {
                                this.SizeChanging(this, new SizeChangeEventArg(e));
                            }
                        }
                        else {
                            if ((e.Column.ColumnName == "FileID")) {
                                if ((this.FileIDChanging != null)) {
                                    this.FileIDChanging(this, new FileIDChangeEventArg(e));
                                }
                            }
                            else {
                                if ((e.Column.ColumnName == "Offset")) {
                                    if ((this.OffsetChanging != null)) {
                                        this.OffsetChanging(this, new OffsetChangeEventArg(e));
                                    }
                                }
                                else {
                                    if ((e.Column.ColumnName == "Status")) {
                                        if ((this.StatusChanging != null)) {
                                            this.StatusChanging(this, new StatusChangeEventArg(e));
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            
            protected override void OnColumnChanged(System.Data.DataColumnChangeEventArgs e) {
                base.OnColumnChanged(e);
                if ((this.SuspendValidation == true)) {
                    return;
                }
                if ((e.Column.ColumnName == "FullName")) {
                    if ((this.FullNameChanged != null)) {
                        this.FullNameChanged(this, new FullNameChangeEventArg(e));
                    }
                }
                else {
                    if ((e.Column.ColumnName == "Hash")) {
                        if ((this.HashChanged != null)) {
                            this.HashChanged(this, new HashChangeEventArg(e));
                        }
                    }
                    else {
                        if ((e.Column.ColumnName == "Size")) {
                            if ((this.SizeChanged != null)) {
                                this.SizeChanged(this, new SizeChangeEventArg(e));
                            }
                        }
                        else {
                            if ((e.Column.ColumnName == "FileID")) {
                                if ((this.FileIDChanged != null)) {
                                    this.FileIDChanged(this, new FileIDChangeEventArg(e));
                                }
                            }
                            else {
                                if ((e.Column.ColumnName == "Offset")) {
                                    if ((this.OffsetChanged != null)) {
                                        this.OffsetChanged(this, new OffsetChangeEventArg(e));
                                    }
                                }
                                else {
                                    if ((e.Column.ColumnName == "Status")) {
                                        if ((this.StatusChanged != null)) {
                                            this.StatusChanged(this, new StatusChangeEventArg(e));
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            
            public void AddDownloadsRow(DownloadsRow row) {
                this.Rows.Add(row);
            }
            
            public DownloadsRow AddDownloadsRow(string FullName, string Hash, long Size, long Offset, short Status) {
                DownloadsRow rowDownloadsRow = ((DownloadsRow)(this.NewRow()));
                rowDownloadsRow.ItemArray = new object[] {
                        FullName,
                        Hash,
                        Size,
                        null,
                        Offset,
                        Status};
                this.Rows.Add(rowDownloadsRow);
                return rowDownloadsRow;
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override System.Data.DataTable Clone() {
                DownloadsDataTable cln = ((DownloadsDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override System.Data.DataTable CreateInstance() {
                return new DownloadsDataTable();
            }
            
            internal void InitVars() {
                this.columnFullName = base.Columns["FullName"];
                this.columnHash = base.Columns["Hash"];
                this.columnSize = base.Columns["Size"];
                this.columnFileID = base.Columns["FileID"];
                this.columnOffset = base.Columns["Offset"];
                this.columnStatus = base.Columns["Status"];
            }
            
            private void InitClass() {
                this.columnFullName = new System.Data.DataColumn("FullName", typeof(string), null, System.Data.MappingType.Element);
                this.columnFullName.ExtendedProperties.Add("Generator_ChangedEventName", "FullNameChanged");
                this.columnFullName.ExtendedProperties.Add("Generator_ChangingEventName", "FullNameChanging");
                this.columnFullName.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "FullName");
                this.columnFullName.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "FullNameColumn");
                this.columnFullName.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnFullName");
                this.columnFullName.ExtendedProperties.Add("Generator_DelegateName", "FullNameChangeEventHandler");
                this.columnFullName.ExtendedProperties.Add("Generator_EventArgName", "FullNameChangeEventArg");
                this.columnFullName.ExtendedProperties.Add("User_ColumnName", "FullName");
                base.Columns.Add(this.columnFullName);
                this.columnHash = new System.Data.DataColumn("Hash", typeof(string), null, System.Data.MappingType.Element);
                this.columnHash.ExtendedProperties.Add("Generator_ChangedEventName", "HashChanged");
                this.columnHash.ExtendedProperties.Add("Generator_ChangingEventName", "HashChanging");
                this.columnHash.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Hash");
                this.columnHash.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "HashColumn");
                this.columnHash.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnHash");
                this.columnHash.ExtendedProperties.Add("Generator_DelegateName", "HashChangeEventHandler");
                this.columnHash.ExtendedProperties.Add("Generator_EventArgName", "HashChangeEventArg");
                this.columnHash.ExtendedProperties.Add("User_ColumnName", "Hash");
                base.Columns.Add(this.columnHash);
                this.columnSize = new System.Data.DataColumn("Size", typeof(long), null, System.Data.MappingType.Element);
                this.columnSize.ExtendedProperties.Add("Generator_ChangedEventName", "SizeChanged");
                this.columnSize.ExtendedProperties.Add("Generator_ChangingEventName", "SizeChanging");
                this.columnSize.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Size");
                this.columnSize.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "SizeColumn");
                this.columnSize.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnSize");
                this.columnSize.ExtendedProperties.Add("Generator_DelegateName", "SizeChangeEventHandler");
                this.columnSize.ExtendedProperties.Add("Generator_EventArgName", "SizeChangeEventArg");
                this.columnSize.ExtendedProperties.Add("User_ColumnName", "Size");
                base.Columns.Add(this.columnSize);
                this.columnFileID = new System.Data.DataColumn("FileID", typeof(int), null, System.Data.MappingType.Element);
                this.columnFileID.ExtendedProperties.Add("Generator_ChangedEventName", "FileIDChanged");
                this.columnFileID.ExtendedProperties.Add("Generator_ChangingEventName", "FileIDChanging");
                this.columnFileID.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "FileID");
                this.columnFileID.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "FileIDColumn");
                this.columnFileID.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnFileID");
                this.columnFileID.ExtendedProperties.Add("Generator_DelegateName", "FileIDChangeEventHandler");
                this.columnFileID.ExtendedProperties.Add("Generator_EventArgName", "FileIDChangeEventArg");
                this.columnFileID.ExtendedProperties.Add("User_ColumnName", "FileID");
                base.Columns.Add(this.columnFileID);
                this.columnOffset = new System.Data.DataColumn("Offset", typeof(long), null, System.Data.MappingType.Element);
                this.columnOffset.ExtendedProperties.Add("Generator_ChangedEventName", "OffsetChanged");
                this.columnOffset.ExtendedProperties.Add("Generator_ChangingEventName", "OffsetChanging");
                this.columnOffset.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Offset");
                this.columnOffset.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "OffsetColumn");
                this.columnOffset.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnOffset");
                this.columnOffset.ExtendedProperties.Add("Generator_DelegateName", "OffsetChangeEventHandler");
                this.columnOffset.ExtendedProperties.Add("Generator_EventArgName", "OffsetChangeEventArg");
                this.columnOffset.ExtendedProperties.Add("User_ColumnName", "Offset");
                base.Columns.Add(this.columnOffset);
                this.columnStatus = new System.Data.DataColumn("Status", typeof(short), null, System.Data.MappingType.Element);
                this.columnStatus.ExtendedProperties.Add("Generator_ChangedEventName", "StatusChanged");
                this.columnStatus.ExtendedProperties.Add("Generator_ChangingEventName", "StatusChanging");
                this.columnStatus.ExtendedProperties.Add("Generator_ColumnPropNameInRow", "Status");
                this.columnStatus.ExtendedProperties.Add("Generator_ColumnPropNameInTable", "StatusColumn");
                this.columnStatus.ExtendedProperties.Add("Generator_ColumnVarNameInTable", "columnStatus");
                this.columnStatus.ExtendedProperties.Add("Generator_DelegateName", "StatusChangeEventHandler");
                this.columnStatus.ExtendedProperties.Add("Generator_EventArgName", "StatusChangeEventArg");
                this.columnStatus.ExtendedProperties.Add("User_ColumnName", "Status");
                base.Columns.Add(this.columnStatus);
                this.columnFileID.AutoIncrement = true;
                this.columnOffset.DefaultValue = ((long)(0));
                this.ExtendedProperties.Add("Generator_RowClassName", "DownloadsRow");
                this.ExtendedProperties.Add("Generator_RowEvArgName", "DownloadsRowChangeEvent");
                this.ExtendedProperties.Add("Generator_RowEvHandlerName", "DownloadsRowChangeEventHandler");
                this.ExtendedProperties.Add("Generator_SuspendValidationPropName", "SuspendValidation");
                this.ExtendedProperties.Add("Generator_SuspendValidationVarName", "m_suspendValidation");
                this.ExtendedProperties.Add("Generator_TableClassName", "DownloadsDataTable");
                this.ExtendedProperties.Add("Generator_TablePropName", "Downloads");
                this.ExtendedProperties.Add("Generator_TableVarName", "tableDownloads");
                this.ExtendedProperties.Add("User_TableName", "Downloads");
            }
            
            public DownloadsRow NewDownloadsRow() {
                return ((DownloadsRow)(this.NewRow()));
            }
            
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new DownloadsRow(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(DownloadsRow);
            }
            
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.DownloadsRowChanged != null)) {
                    this.DownloadsRowChanged(this, new DownloadsRowChangeEvent(((DownloadsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.DownloadsRowChanging != null)) {
                    this.DownloadsRowChanging(this, new DownloadsRowChangeEvent(((DownloadsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.DownloadsRowDeleted != null)) {
                    this.DownloadsRowDeleted(this, new DownloadsRowChangeEvent(((DownloadsRow)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.DownloadsRowDeleting != null)) {
                    this.DownloadsRowDeleting(this, new DownloadsRowChangeEvent(((DownloadsRow)(e.Row)), e.Action));
                }
            }
            
            public void RemoveDownloadsRow(DownloadsRow row) {
                this.Rows.Remove(row);
            }
            
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                FilesDataSet ds = new FilesDataSet();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "DownloadsDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
            
            public delegate void FullNameChangeEventHandler(DownloadsDataTable sender, FullNameChangeEventArg e);
            
            public class FullNameChangeEventArg : System.EventArgs {
                
                private System.Data.DataColumnChangeEventArgs evArgs;
                
                public FullNameChangeEventArg(System.Data.DataColumnChangeEventArgs args) {
                    this.evArgs = args;
                }
                
                public DownloadsRow Row {
                    get {
                        return ((DownloadsRow)(this.evArgs.Row));
                    }
                }
                
                public System.Data.DataColumn FullNameColumn {
                    get {
                        return this.evArgs.Column;
                    }
                }
                
                public string ProposedValue {
                    get {
                        return ((string)(this.evArgs.ProposedValue));
                    }
                    set {
                        this.evArgs.ProposedValue = ((string)(value));
                    }
                }
            }
            
            public delegate void HashChangeEventHandler(DownloadsDataTable sender, HashChangeEventArg e);
            
            public class HashChangeEventArg : System.EventArgs {
                
                private System.Data.DataColumnChangeEventArgs evArgs;
                
                public HashChangeEventArg(System.Data.DataColumnChangeEventArgs args) {
                    this.evArgs = args;
                }
                
                public DownloadsRow Row {
                    get {
                        return ((DownloadsRow)(this.evArgs.Row));
                    }
                }
                
                public System.Data.DataColumn HashColumn {
                    get {
                        return this.evArgs.Column;
                    }
                }
                
                public string ProposedValue {
                    get {
                        return ((string)(this.evArgs.ProposedValue));
                    }
                    set {
                        this.evArgs.ProposedValue = ((string)(value));
                    }
                }
            }
            
            public delegate void SizeChangeEventHandler(DownloadsDataTable sender, SizeChangeEventArg e);
            
            public class SizeChangeEventArg : System.EventArgs {
                
                private System.Data.DataColumnChangeEventArgs evArgs;
                
                public SizeChangeEventArg(System.Data.DataColumnChangeEventArgs args) {
                    this.evArgs = args;
                }
                
                public DownloadsRow Row {
                    get {
                        return ((DownloadsRow)(this.evArgs.Row));
                    }
                }
                
                public System.Data.DataColumn SizeColumn {
                    get {
                        return this.evArgs.Column;
                    }
                }
                
                public long ProposedValue {
                    get {
                        return ((long)(this.evArgs.ProposedValue));
                    }
                    set {
                        this.evArgs.ProposedValue = ((long)(value));
                    }
                }
            }
            
            public delegate void FileIDChangeEventHandler(DownloadsDataTable sender, FileIDChangeEventArg e);
            
            public class FileIDChangeEventArg : System.EventArgs {
                
                private System.Data.DataColumnChangeEventArgs evArgs;
                
                public FileIDChangeEventArg(System.Data.DataColumnChangeEventArgs args) {
                    this.evArgs = args;
                }
                
                public DownloadsRow Row {
                    get {
                        return ((DownloadsRow)(this.evArgs.Row));
                    }
                }
                
                public System.Data.DataColumn FileIDColumn {
                    get {
                        return this.evArgs.Column;
                    }
                }
                
                public int ProposedValue {
                    get {
                        return ((int)(this.evArgs.ProposedValue));
                    }
                    set {
                        this.evArgs.ProposedValue = ((int)(value));
                    }
                }
            }
            
            public delegate void OffsetChangeEventHandler(DownloadsDataTable sender, OffsetChangeEventArg e);
            
            public class OffsetChangeEventArg : System.EventArgs {
                
                private System.Data.DataColumnChangeEventArgs evArgs;
                
                public OffsetChangeEventArg(System.Data.DataColumnChangeEventArgs args) {
                    this.evArgs = args;
                }
                
                public DownloadsRow Row {
                    get {
                        return ((DownloadsRow)(this.evArgs.Row));
                    }
                }
                
                public System.Data.DataColumn OffsetColumn {
                    get {
                        return this.evArgs.Column;
                    }
                }
                
                public long ProposedValue {
                    get {
                        return ((long)(this.evArgs.ProposedValue));
                    }
                    set {
                        this.evArgs.ProposedValue = ((long)(value));
                    }
                }
            }
            
            public delegate void StatusChangeEventHandler(DownloadsDataTable sender, StatusChangeEventArg e);
            
            public class StatusChangeEventArg : System.EventArgs {
                
                private System.Data.DataColumnChangeEventArgs evArgs;
                
                public StatusChangeEventArg(System.Data.DataColumnChangeEventArgs args) {
                    this.evArgs = args;
                }
                
                public DownloadsRow Row {
                    get {
                        return ((DownloadsRow)(this.evArgs.Row));
                    }
                }
                
                public System.Data.DataColumn StatusColumn {
                    get {
                        return this.evArgs.Column;
                    }
                }
                
                public short ProposedValue {
                    get {
                        return ((short)(this.evArgs.ProposedValue));
                    }
                    set {
                        this.evArgs.ProposedValue = ((short)(value));
                    }
                }
            }
        }
        
        public class SharesRow : System.Data.DataRow {
            
            private SharesDataTable tableShares;
            
            internal SharesRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableShares = ((SharesDataTable)(this.Table));
            }
            
            public string FullName {
                get {
                    return ((string)(this[this.tableShares.FullNameColumn]));
                }
                set {
                    this[this.tableShares.FullNameColumn] = value;
                }
            }
            
            public string Hash {
                get {
                    try {
                        return ((string)(this[this.tableShares.HashColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("StrongTyping_CannotAccessDBNull", e);
                    }
                }
                set {
                    this[this.tableShares.HashColumn] = value;
                }
            }
            
            public System.DateTime LastModified {
                get {
                    try {
                        return ((System.DateTime)(this[this.tableShares.LastModifiedColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("StrongTyping_CannotAccessDBNull", e);
                    }
                }
                set {
                    this[this.tableShares.LastModifiedColumn] = value;
                }
            }
            
            public long Size {
                get {
                    try {
                        return ((long)(this[this.tableShares.SizeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("StrongTyping_CannotAccessDBNull", e);
                    }
                }
                set {
                    this[this.tableShares.SizeColumn] = value;
                }
            }
            
            public bool Keep {
                get {
                    try {
                        return ((bool)(this[this.tableShares.KeepColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("StrongTyping_CannotAccessDBNull", e);
                    }
                }
                set {
                    this[this.tableShares.KeepColumn] = value;
                }
            }
            
            public bool IsHashNull() {
                return this.IsNull(this.tableShares.HashColumn);
            }
            
            public void SetHashNull() {
                this[this.tableShares.HashColumn] = System.Convert.DBNull;
            }
            
            public bool IsLastModifiedNull() {
                return this.IsNull(this.tableShares.LastModifiedColumn);
            }
            
            public void SetLastModifiedNull() {
                this[this.tableShares.LastModifiedColumn] = System.Convert.DBNull;
            }
            
            public bool IsSizeNull() {
                return this.IsNull(this.tableShares.SizeColumn);
            }
            
            public void SetSizeNull() {
                this[this.tableShares.SizeColumn] = System.Convert.DBNull;
            }
            
            public bool IsKeepNull() {
                return this.IsNull(this.tableShares.KeepColumn);
            }
            
            public void SetKeepNull() {
                this[this.tableShares.KeepColumn] = System.Convert.DBNull;
            }
        }
        
        public class DownloadsRow : System.Data.DataRow {
            
            private DownloadsDataTable tableDownloads;
            
            internal DownloadsRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableDownloads = ((DownloadsDataTable)(this.Table));
            }
            
            public string FullName {
                get {
                    try {
                        return ((string)(this[this.tableDownloads.FullNameColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("StrongTyping_CannotAccessDBNull", e);
                    }
                }
                set {
                    this[this.tableDownloads.FullNameColumn] = value;
                }
            }
            
            public string Hash {
                get {
                    try {
                        return ((string)(this[this.tableDownloads.HashColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("StrongTyping_CannotAccessDBNull", e);
                    }
                }
                set {
                    this[this.tableDownloads.HashColumn] = value;
                }
            }
            
            public long Size {
                get {
                    try {
                        return ((long)(this[this.tableDownloads.SizeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("StrongTyping_CannotAccessDBNull", e);
                    }
                }
                set {
                    this[this.tableDownloads.SizeColumn] = value;
                }
            }
            
            public int FileID {
                get {
                    try {
                        return ((int)(this[this.tableDownloads.FileIDColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("StrongTyping_CannotAccessDBNull", e);
                    }
                }
                set {
                    this[this.tableDownloads.FileIDColumn] = value;
                }
            }
            
            public long Offset {
                get {
                    try {
                        return ((long)(this[this.tableDownloads.OffsetColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("StrongTyping_CannotAccessDBNull", e);
                    }
                }
                set {
                    this[this.tableDownloads.OffsetColumn] = value;
                }
            }
            
            public short Status {
                get {
                    try {
                        return ((short)(this[this.tableDownloads.StatusColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("StrongTyping_CannotAccessDBNull", e);
                    }
                }
                set {
                    this[this.tableDownloads.StatusColumn] = value;
                }
            }
            
            public bool IsFullNameNull() {
                return this.IsNull(this.tableDownloads.FullNameColumn);
            }
            
            public void SetFullNameNull() {
                this[this.tableDownloads.FullNameColumn] = System.Convert.DBNull;
            }
            
            public bool IsHashNull() {
                return this.IsNull(this.tableDownloads.HashColumn);
            }
            
            public void SetHashNull() {
                this[this.tableDownloads.HashColumn] = System.Convert.DBNull;
            }
            
            public bool IsSizeNull() {
                return this.IsNull(this.tableDownloads.SizeColumn);
            }
            
            public void SetSizeNull() {
                this[this.tableDownloads.SizeColumn] = System.Convert.DBNull;
            }
            
            public bool IsFileIDNull() {
                return this.IsNull(this.tableDownloads.FileIDColumn);
            }
            
            public void SetFileIDNull() {
                this[this.tableDownloads.FileIDColumn] = System.Convert.DBNull;
            }
            
            public bool IsOffsetNull() {
                return this.IsNull(this.tableDownloads.OffsetColumn);
            }
            
            public void SetOffsetNull() {
                this[this.tableDownloads.OffsetColumn] = System.Convert.DBNull;
            }
            
            public bool IsStatusNull() {
                return this.IsNull(this.tableDownloads.StatusColumn);
            }
            
            public void SetStatusNull() {
                this[this.tableDownloads.StatusColumn] = System.Convert.DBNull;
            }
        }
        
        public class SharesRowChangeEvent : System.EventArgs {
            
            private SharesRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            public SharesRowChangeEvent(SharesRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public SharesRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
        
        public class DownloadsRowChangeEvent : System.EventArgs {
            
            private DownloadsRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            public DownloadsRowChangeEvent(DownloadsRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public DownloadsRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
